### ISSUE TITLE
what happened to out putting text ?

### ISSUE THREAD

**Issue by oziee** [snipsco/snips-platform-documentation#10]
Snips used to output the ASR text of what it heard, no matter if it could NLU to the sentence via MQTT

now MQTT just says [Asr] captured text "unknownword"

bit hard to debug or even use Snips for other apps rather then be confined to the snips skills eco system

**Comment by dstolpmann** [comment]
Hi,
by default, Snips' built-in voice recognition does only detect words you used in the training examples of your assistant. If you want Snips to recognize more words, please refer to https://github.com/snipsco/snips-platform-documentation/wiki/6.--Miscellaneous#using-snips-generic-asr-model-english-only to get more information on how to install a generic ASR model.

Best regards,
dstolpmann

**Comment by goo** [comment]
Yes "unknownword" as an output means the word was not recognized. Ensure all the vocabulary you want to support is part of your assistant.
