### ISSUE TITLE
docker run error after doing a docker pull --- Couldn't find any assistant

### ISSUE THREAD

**Issue by ravikokku** [snipsco/snips-platform-documentation#13]
The assistant is exactly in the same location as before the pull, but the following error got introduced after the pull.

$docker --debug run -t --rm --name snips --log-driver none -p 9898:1883 -v /home/pi/.asoundrc:/root/.asoundrc -v /opt/snips/config:/opt/snips/config --privileged -v /dev/snd:/dev/snd snipsdocker/platform
Couldn't find any assistant
DEBU[0001] [hijack] End of stdout                       

ASSISTANT:

$ls -la /opt/snips/config/assistant/

total 116
drwxr-xr-x 4 root root  4096 Nov  5 22:39 .
drwxr-xr-x 3 root root  4096 Nov  5 22:39 ..
-rw-r--r-- 1 root root   849 Nov  6  2017 assistant.json
drwxr-xr-x 2 root root  4096 Nov  5 22:39 custom_asr
drwxr-xr-x 2 root root  4096 Nov  5 22:39 custom_hotword
-rw-r--r-- 1 root root  8428 Nov  6  2017 dataset.json
-rw-r--r-- 1 root root 83380 Nov  6  2017 trained_assistant.json

**Comment by 4OH4** [comment]
Having the same issue, after following these instructions: https://medium.com/snips-ai/build-a-weather-assistant-with-snips-4253541f1684.
Problem with the latest image?

**Comment by ratamovic** [comment]
@ravikokku Beware last release has changed the assistant mount point to `/usr/share/snips/assistant`. So I think you should replace `-v /opt/snips/config:/opt/snips/config` with something like `-v /opt/snips/config/assistant:/usr/share/snips/assistant`.
The current docker section of snips-platform-documentation is incorrect on that subject and is going to be fixed.

@4OH4 Beware the [build a weather assistant](https://medium.com/snips-ai/build-a-weather-assistant-with-snips-4253541f1684) blog post is now outdated with latest release.
