### ISSUE TITLE
Only Smart lights bundle avaible

### ISSUE THREAD

**Issue by andlo** [snipsco/snips-platform-documentation#14]
I wanted to make a test using the weather bundle, but I dont see that bundle - what am I dooing wrong ?

**Comment by andlo** [comment]
Hi @JDureau 
Nope - I am under Store :( some days ago I did have more bundles in the store...But maybe I did something not so smart....but only one bundle now....

**Comment by andlo** [comment]
<img width="790" alt="udklip" src="https://user-images.githubusercontent.com/3314671/32794116-3c967af6-c968-11e7-9dfb-567ef6048841.PNG">

**Comment by pocketjoso** [comment]
@andlo What is the language of your assistant? The bundles are language dependant, so it's possible that you have selected a language in which we haven't yet published any bundles.

If not, please try to refresh the page and tell us whether the problem persists.

**Comment by andlo** [comment]
@pocketjoso It is English. tryed to delete and create new assistant  - same probem.

Maybe I should try makeing new snips.ai account....

**Comment by pocketjoso** [comment]
@andlo Did you first try to refresh the page and click back into the store? It's possible that you came upon an unexpected error that prevent the store content from loading as it should.

**Comment by andlo** [comment]
Solved....Dont know how, but flushing cache, restarting PC did something...Strange, but I am happy.

**Comment by pocketjoso** [comment]
Okay, glad it's working again - just come back and re-open this should the issue ever re-appear!
