### ISSUE TITLE
code out of date

### ISSUE THREAD

**Issue by oziee** [snipsco/snips-platform-documentation#15]
with all the new changes to Snips the example codes at https://github.com/snipsco/snips-platform-documentation/tree/master/python are no longer valid

The JSON tts etc now requires siteId etc

**Comment by MaureenMo** [comment]
Hi !
Would you know what needs to be changes in the old handler code ?
I'm having issues with it.
Don't know if that is linked to the old version but I get the following error :  socket.error: [Errno 111] Connection refused
Thanks

**Comment by goo** [comment]
Code has been updated, tx
