### ISSUE TITLE
Hotword sensitivity configuration

### ISSUE THREAD

**Issue by a7ypically** [snipsco/snips-platform-documentation#19]
Hi,

Any way to set the sensitivity? For me the false positive is currently too high.

Thanks.

**Comment by dstolpmann** [comment]
Hi,
you can change the sensitivity of the hotword detection in the configuration file, which is located by default at `/etc/snips.toml `. In the section `[snips-hotword]`, you can find the parameter `sensitivity`, which should do exactly what you want. The parameter can take a value between 0 and 1 (a higher value means more sensitive). Do not forget to remove any leading number signs as they mark a comment.

For more information on the available options, please refer to:
https://github.com/snipsco/snips-platform-documentation/wiki/6.--Miscellaneous#platform-configuration

Best regards,
dstolpmann
