### ISSUE TITLE
Packages error ubuntu

### ISSUE THREAD

**Issue by 76MPaul** [snipsco/snips-platform-documentation#25]
Hi guys, 

I try to install snips on my ubuntu 16.04 and find myself stuck on "Err:12 https://debian.snips.ai/xenial stable/main amd64 Packages   404  Not Found " after apt-get upadte.
The repository 'https://debian.snips.ai/xenial stable Release' does not have a Release file.

I read somewhere that it should be working. Did I make a mistake ? 

Thanks in advance, 

regards, 

76MPaul

**Comment by tschmidty69** [comment]
Hmm, they only seem to support jessie on amd64 so it seems you would need to use 15.10. You could try editing the /etc/apt/repos.d/snips.cfg (or whatever it is) and pointing it to jessie but no clue if it would work.

**Comment by 76MPaul** [comment]
Hi !

Thanks for the help, I manage to install the jessie version by modifying in /etc/apt/sources.list.d/snips.list
the line into deb https://debian.snips.ai/jessie stable main

And it work ! 

76MPaul
