### ISSUE TITLE
Unable to read file trained_assisstant.json because missing field language

### ISSUE THREAD

**Issue by vp** [snipsco/snips-platform-documentation#29]
I'm unable to set up snips in docker on rpi 3 or rpi zero w. Tested on raspbian jessie lite (downloaded from link provided in documentation) or last stretch version. 

In both cases snips-queries exits with error: 
Unable to read file '/usr/share/snips/assistant/trained_assistant.json"
Caused by: missing field language at line 1 column 208570

Tested with two generated assistants with the same results.

**Comment by vp** [comment]
snipsdocker/platform:arm-latest works

**Comment by s1nu5** [comment]
I have the same problem, but I can't figure your solution out. Could you elaborate a bit more, please?
