### ISSUE TITLE
ERROR:snips_dialogue

### ISSUE THREAD

**Issue by arpitbaheti** [snipsco/snips-platform-documentation#3]
[12:38:54.830155] ERROR:snips_dialogue: DialogueError(Serde(ErrorImpl { code: Message("missing field `entity`"), line: 1409, column: 17 }), State { next_error: None })

**Comment by hdlj** [comment]
Hello @arpitbaheti, 

Thanks for reporting this issue.

Could you send me the assistant.json to hubert.delajonquiere@snips.ai or on this channel (if it doesn't contain confidential data)?

**Comment by arpitbaheti** [comment]
Sent you the assistant zip file, please let me know whats the issue. Thanks!

**Comment by hdlj** [comment]
Thanks! The issue has been fixed. You need to download again the assistant on the platform.

**Comment by arpitbaheti** [comment]
Thanks will try again!

**Comment by scooter1556** [comment]
I am getting this exact error multiple times when I start the latest docker image on an assistant downloaded today. I have been configuring and downloading different assistants, removing intents, adding intents, re-training but I get this error with snips-dialogue regarding the missing 'entity' field every time no what the assistant configuration.

Any ideas?

**Comment by fredszaq** [comment]
Hi @scooter1556 we had a problem on the assistant.json generation, should be fixed now (you need to retrain an redownload your assistant)
