### ISSUE TITLE
Error in trained_assistant.json file

### ISSUE THREAD

**Issue by steph1793** [snipsco/snips-platform-documentation#34]
Hi, I get this error, when I start snips:
Error: Unable to read file `"/usr/share/snips/assistant/trained_assistant.json"`
Caused by: missing field `language` at line 1 column 2181822

Every step before this error works perfectly ( connection to mqtt broker).
Can you please help me, I have spent almost a week on this issue.
Thank you.

Here is the assistant zip file : 
https://drive.google.com/open?id=1qswQ9bgTdRt5IWB_GsEEwYNDWZqCI61w

**Comment by s1nu5** [comment]
[It's hard to miss that one](https://github.com/snipsco/snips-platform-documentation/issues/29)

**Comment by steph1793** [comment]
Indeed , lol.
Thank you for answering.
Can you please elaborate the solution a bit more , @s1nu5 ? I am a very new user of snips.
Thank you in advance.

**Comment by steph1793** [comment]
I figured out. I just had to remove snipsdocker/platform:latest image. And docker pull snipsdocker/platform:arm-latest.
Thanks a lot
