### ISSUE TITLE
Missing examples for rich interactions

### ISSUE THREAD

**Issue by alicbelmin** [snipsco/snips-platform-documentation#38]
Hello,

I am trying to set up any kind of interaction scenario with Snips. Mainly, I want the assistant to give me any kind of response. I was reading the tutorial about this (https://github.com/snipsco/snips-platform-documentation/wiki/5.-Build-rich-interactions), but since there is no real instruction set or example, I am unable to understand what to do.
Could someone help me out?

Thanks,
Belmin Alic.

**Comment by goo** [comment]
Hi Alic, thanks for your interest.
For this kind of support, please join our snips server on Discord (https://discordapp.com/invite/3939Kqx), you will have access to all the knowledge of our community!
