### ISSUE TITLE
string slots type

### ISSUE THREAD

**Issue by Darune** [snipsco/snips-platform-documentation#4]
Hi, 
When trying to create a custom intent, 
It seems like the `snips/default` slot type is not considered a valid one, is there any way to add a string slot type ? am i missing something ? 
I get the following error when trying to select the `snips/default` slot type 
```Error: Slots: [slot_1_name, slot_2_name] are missing required slot type```

**Comment by adrienball** [comment]
Hi @Darune, thanks for reporting this issue.
We are currently fixing it, in the meantime you can create a custom slot_type by typing the desired name in the slot_type form like below, and click on the create option:
![image](https://user-images.githubusercontent.com/11029979/27324047-24f6fcfa-55a4-11e7-9da6-87e2ccf078da.png)

**Comment by adrienball** [comment]
Hey @Darune we have fixed the issue, you can start using `snips/default` slot type again.
Thanks again.
