### ISSUE TITLE
Boosting ASR - Not receiving partialTextCaptured message from asr

### ISSUE THREAD

**Issue by GiovanniBalestrieri** [snipsco/snips-platform-documentation#40]
Hi,
Thank you for this software.

I would like to make the Snips' Automatic Speech Recognition fastest. There is a small delay, ~ 5 seconds, between the last spoken word and the message being published on the /hermes/asr/textCaptured topic. I have been looking for some parameters to decrease this delay with no success.

Then I found another topic the ASR is supposed to publish partial results of the recognition to. I subscribed to hermes/asr/partialTextCaptured but got no messages.

Is it possible to decrease this delay by tuning some configuration parameters or by using the PartialTextCaptured?

Thanks

**Comment by kali** [comment]
Hey UserK, thanks for your interest.

~5 seconds is not the experience you should have. Please allow me to go through a few trivial checks with you first. Also, know that the current version (which is right now crippled by a few glitches that we are hunting, so don't rush the install) shows a significant improvement on the ASR startup time.

* Are you using a raspberry pi 3 ?

* Can you check which version of libatlas-base3 you have installed ?
```
pi@raspberrypi-kali:~ $ dpkg -l | grep atlas3
ii  libatlas3-base                  3.10.3-1-snips                    armhf        Automatically Tuned Linear Algebra Software, generic shared
```
The version number should be 3.10.3-1-snips.

* Is there a screen connected to your PI on the HDMI output ? If so, can you check for the presence of a thunderbold or thermometer icon on the top right corner ? This is an indication of an inadequate power supply or overheating, and is more likely to happen than you may think.

* Can you check at what frequency your pi is running when snips platform is operating ? `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` should show 1200000 .

Thanks :)

**Comment by GiovanniBalestrieri** [comment]
Good morning Kali,

- Are you using a raspberry pi 3? Yes I am using it
- version of libatlas-base3: This  is the output of the command:
`ii  libatlas3-base                       3.10.3-1+rpi1                     armhf        Automatically Tuned Linear Algebra Software, generic shared
- Is there a screen connected to your PI on the HDMI output ? 
I am not using a screen but we I am using a power supply connected to the USB port. 

- frequency your pi is running:
```
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
600000
```
Thank you for your support

**Comment by kali** [comment]
OK, first order of business, you need to run "our" atlas. `apt-get install libatlas3-base` should pick it.

It should be way faster.

**Comment by GiovanniBalestrieri** [comment]
Thanks, so I guess I can push it further by increasing cpu frequency. 
Yes I have noticed an improvement in the overall detection time.
What about the partialTextCaptured intent not being published, is there an option to enable this feature?

**Comment by kali** [comment]
We have not advertised it, because we could not make it efficient enough. Computing partial results is actually quite expensive, too expensive for a raspberry pi 3.

**Comment by GiovanniBalestrieri** [comment]
Ok thank you very much

**Comment by GiovanniBalestrieri** [comment]
Hi Kali,
I don't if this issue is related to the new version of libatlas-base but I ran into this problem:

```
systemd[1]: Started Snips ASR.
snips-asr[1503]: /usr/bin/snips-asr: error while loading shared libraries: libsnips-kaldi.so: cannot open shared object file: No such file or directory
systemd[1]: snips-asr.service: Main process exited, code=exited, status=127/n/a
systemd[1]: snips-asr.service: Unit entered failed state.
systemd[1]: snips-asr.service: Failed with result 'exit-code'.
```

**Comment by kali** [comment]
You probably have a partial installation missing snips-kaldi.

I run this to check what I have installed:

```
pi@raspberrypi-kali:~ $ dpkg -l | grep ii | grep snips
ii  libatlas3-base                  3.10.3-1-snips                    armhf        Automatically Tuned Linear Algebra Software, generic shared
ii  libtensorflow                   1.3.1-snips-1                     armhf        Tensorflow C library
ii  snips-analytics                 0.53.17                           armhf        Snips Analytics CLI
ii  snips-asr                       0.53.17                           armhf        Snips Automatic Speech Recognition
ii  snips-audio-server              0.53.17                           armhf        Snips audio server
ii  snips-dialogue                  0.53.17                           armhf        A cli tool to run Snips Dialogue Manager
ii  snips-hotword                   0.53.17                           armhf        A cli tool to run Snips Hotword activation
ii  snips-kaldi-atlas               0.20.3                            armhf        Snips/Kaldi C/C++ wrapper
ii  snips-nlu                       0.53.17                           armhf        Snips snips-nlu command line interface
ii  snips-platform-common           0.53.17                           armhf        Base package for configuration
ii  snips-platform-demo             0.53.17                           armhf        GetWeather (EN) Demo assistant
ii  snips-platform-voice            0.53.17                           armhf        Metapackage for snips-platform voice assistant
ii  snips-tts                       0.53.17                           armhf        Snips TTS CLI
```
