### ISSUE TITLE
Clean install from scratch on raspberry pi does not work

### ISSUE THREAD

**Issue by cyph-zz** [snipsco/snips-platform-documentation#41]
Here is the context :
Raspbian stretch from 2018-03-13 clean install.
wifi, ssh and vnc activation
curl https://install.snips.ai -sSf | sh

Everything installed properly.
Assistant Installation was also ok.

1) First issue was encountered, I got a permission denied on docker -> solved by adding user to docker.
2) Second issue also solved : I could not find the assistant -> solved by changing /usr/bin/snips last line on the docker launch, I changed the -v option to this -v /opt/snips/config:/usr/share/snips
3) Third issue logs :  

`2018-03-23 17:56:56,690 INFO exited: snips-dialogue (exit status 1; not expected)
Error: Unable to read file `"/usr/share/snips/assistant/trained_assistant.json"`
Caused by: missing field `language` at line 1 column 3033823
`
solved reading another thread and editing /usr/bin/snips last line : change the plateform to arm-latest

But now : it still produces a recurring error : 
`INFO:hermes_mqtt  : Connecting to MQTT broker at address localhost:1883
INFO:rumqtt::connection: $$$ Connected to broker
INFO:hermes_mqtt       : Connecting to MQTT broker at address localhost:1883
INFO:rumqtt::connection: $$$ Connected to broker
INFO:snips_hotword     : Connecting using MQTT site-id default
snips_stt --use-energy=false --num-mel-bins=40 --num-ceps=40 --low-freq=20 --high-freq=-400 --sample-frequency=16000 
INFO:hermes_mqtt: Connecting to MQTT broker at address localhost:1883
Error: Given model version 0.13.0 doesn't match. Expected model version 0.12.0

ERROR:rumqtt::connection: MQTT Error TryRecv(Disconnected)
2018-03-23 18:08:06,048 INFO exited: snips-queries (exit status 1; not expected)
INFO:rumqtt::connection: $$$ Connected to broker
2018-03-23 18:08:06,110 INFO spawned: 'snips-queries' with pid 106
INFO:hermes_mqtt       : Connecting to MQTT broker at address localhost:1883
INFO:rumqtt::connection: $$$ Connected to broker
INFO:snips_asr         : Connecting using MQTT site-id default
INFO:snips_asr_hermes  : Preparing decoder
INFO:hermes_mqtt: Connecting to MQTT broker at address localhost:1883
INFO:rumqtt::connection: $$$ Connected to broker
INFO:queries_hermes    : loading model at path "/usr/share/snips/assistant"
INFO:snips_asr_hermes  : Idle
2018-03-23 18:08:07,843 INFO success: snips-queries entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Error: Given model version 0.13.0 doesn't match. Expected model version 0.12.0

2018-03-23 18:08:11,023 INFO exited: snips-queries (exit status 1; not expected)
2018-03-23 18:08:12,030 INFO spawned: 'snips-queries' with pid 120
INFO:hermes_mqtt: Connecting to MQTT broker at address localhost:1883
INFO:rumqtt::connection: $$$ Connected to broker
INFO:queries_hermes    : loading model at path "/usr/share/snips/assistant"
2018-03-23 18:08:13,190 INFO success: snips-queries entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Error: Given model version 0.13.0 doesn't match. Expected model version 0.12.0
`

what's wrong with models ?

**Comment by goo** [comment]
This installation procedure is deprecated.
Please refer to https://github.com/snipsco/snips-platform-documentation/wiki for a clean installation.
Sorry for that.
