### ISSUE TITLE
Cannot detect intents snips-nlu.service version model mismatch 

### ISSUE THREAD

**Issue by GiovanniBalestrieri** [snipsco/snips-platform-documentation#51]
I updated a skill, downloaded from the website and installed it manually. Now I am running into an issue related to model version mismatch.

Here is the log report:

> May  9 12:11:33 histamin snips-nlu[11943]: INFO:snips_nlu_hermes: loading model at path "/usr/share/snips/assistant"
> May  9 12:11:34 histamin snips-nlu[11943]: Error: Given model version 0.14.0 doesn't match. Expected model version 0.13.0
> May  9 12:11:34 histamin snips-nlu[11943]: ERROR:rumqtt::client  : Disconnected: (Error(SyncMpsc(Disconnected), State { next_error: None, backtrace: None }))
> May  9 12:11:34 histamin systemd[1]: snips-nlu.service: Main process exited, code=exited, status=1/FAILURE
> May  9 12:11:34 histamin systemd[1]: snips-nlu.service: Unit entered failed state.
> May  9 12:11:34 histamin systemd[1]: snips-nlu.service: Failed with result 'exit-code'.
> May  9 12:11:39 histamin systemd[1]: snips-nlu.service: Service hold-off time over, scheduling restart.
> May  9 12:11:39 histamin systemd[1]: Stopped Snips NLU.

I have tried changing the model version in the assistant.json file to 0.13 but I am still getting this error after a `sudo systemctl restart "snips-*"`

How do I fix this problem?
Thanks

**Comment by adrienball** [comment]
Hi @GiovanniBalestrieri, you need to update the snips-platform on your device so that it's aligned with the version used during training on the web console. The error message is indeed not clear, we will improve that in the coming releases.
Cheers

**Comment by GiovanniBalestrieri** [comment]
Ok I solved by updating snips
thank you
