### ISSUE TITLE
Bed pressure sensing

### ISSUE THREAD

**Issue by Aephir** [snipsco/snips-platform-documentation#56]
Don't want a different mattress, but just some type of pressure sensor for putting under the mattress.

E.g.: https://www.smarthome.com/united-security-products-901pr-60lb-pre-wired-pressure-mat-9x15.html

https://www.amazon.com/United-Security-Products-903PR-Pre-Wired/dp/B00496BI16/

http://www.arun-electronics.co.uk/pressure_mat.htm

**Comment by peteh** [comment]
So hat is your question?

**Comment by Aephir** [comment]
Sorry, I'm also using this as a "note to self" for things I want to implement/look into/fix/etc.... I'm looking at which pressure sensor/mat would work best for sensing who is in bed (left/right side).
