### ISSUE TITLE
using specific parts of Snips only

### ISSUE THREAD

**Issue by oziee** [snipsco/snips-platform-documentation#8]
trying to use snips but only the hotword detection and the speech recognition parts.. I don't needs the tts and use my own NLU system

docker run -t --rm --name snips --log-driver none -p 9898:1883 -v /home/pi/.asoundrc:/root/.asoundrc -v /opt/snips/config:/opt/snips/config --privileged -v /dev/snd:/dev/snd snipsdocker/platform --include-components "snips-hotword,snips-dialogue,snips-asr"

snips runs.. but does not work
ERROR:snips_hotword     : Error: Cannot assign requested address (os error 99)
INFO exited: snips-hotword (exit status 1; not expected)

these errors repeat over and over.. hotword doesn't work obviously.. but even sending a MQTT to start the ASR to listen "hermes/asr/toggleOn" doesn't work either

**Comment by codeundercoverdev** [comment]
Has anyone responded to this?  I have a similar issue - I only want to use the SNIPS offline speech recognition and nothing else.

**Comment by kali** [comment]
Hey !

You should try out the "new" way to install snips: it's now based on APT, so you can install the whole platform, or cherrypick the few components you want. It's now much easier than it used to be with the docker install.

Keep us posted is you run into problem, here on slack, and we'll try to help.
